### PR TITLE
[cleanup] replace address and registers with const

### PR DESCRIPTION
**Pull request by erik-smit**
i was having some trouble understanding the code
what do you think about this?

i'd also like to replace the bit-fiddling with constants in the style of: https://github.com/ReclaimerLabs/FUSB302/blob/master/FUSB302.h#L38-L45

### CODE REVIEW

**Comment by CRImier** [comment]
Yes, that works wonders! I was already thinking of that. My personal TODO is using micropython `const` keyword, but it's not required. Thank you, merging!

**Comment by CRImier** [comment]
Thank you for your contribution! ^~^ As for constants.. Honestly, that sounds like it's starting to be a lot of variables given it's like, 100 extra variables? I'd much rather have this info be as comments, which, I'm trying to add, and you're also welcome to!

**Comment by erik-smit** [comment]
Awesome! Thanks a lot for this project! I've been using it to experiment with some proprietary UVDM bits. Altmode has been very helpful! 

Next step, trying to figure out how to function as a source/host. Fiddling with the pullups, hostcur, toggle, etc. hasn't yet been a success but it seems doable.

**Comment by CRImier** [comment]
oh oh I have the power source code done and working! just need to uhhh upload it :sweat_smile: put on immediate TODO!

**Comment by CRImier** [comment]
@erik-smit I have uploaded the PSU code and merged your commits into that! It mostly works, is charging my laptop as I write this reply! Also makes the code more verbose - a bit of print cleanup called for. Apologies if I haven't updated that code to keep up with your changes, I'm low on energy so I have to cull my perfectionism. It also adds data and power rule support into at least messages,, don't recall if this applies to automatic GoodCRC responses tho, haven't yet sniffed the code, do send a PR if this isn't the case and I forgot to change some FUSB reg.

Now, your second PR, I need to respond to that sometime soon. In the meantime, I hope this helps. ^~^

**Comment by erik-smit** [comment]
@CRImier very cool, i've integrated it into my consts-PR. it helps me understand what's going on

**Pull request merged**
